export const places = [
  {
    id: 1,
    title: 'Otra labor Ecohñan',
    subtitle: 'Otra labor Ecohñan',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249296/Pukaqaqa/otraLabor_farlse.jpg',
    x: 314,
    y: 278,
  },
  {
    id: 2,
    title: 'Tajo abierto',
    subtitle:
      'Vista desde el aire tajo abierto Mónica Empresa Comunal Hatun Ñan',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249297/Pukaqaqa/tajoAbierto_smvuyg.jpg',
    x: 300,
    y: 322,
  },
  {
    id: 3,
    title: 'Trabajos',
    subtitle: 'Trabajadores en el tajo abierto Mónica',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249298/Pukaqaqa/trabajos_qxgznv.jpg',
    x: 290,
    y: 350,
  },
  {
    id: 4,
    title: 'Tajo abierto',
    subtitle: 'Tajo abierto Mónica',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249298/Pukaqaqa/tajoAbiertoMonica_vogj5y.jpg',
    x: 270,
    y: 357,
  },
  {
    id: 5,
    title: 'Maquinaria',
    subtitle:
      'Cargadores frontales en el tajo abierto Mónica con logo de Ecohñan',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249296/Pukaqaqa/maquinarias_cite3p.jpg',
    x: 247,
    y: 363,
  },
  {
    id: 6,
    title: 'Reunión de trabajadores',
    subtitle: 'Reunión de trabajadores en el tajo abierto',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249297/Pukaqaqa/reunionTrabajadores_bqben4.jpg',
    x: 229,
    y: 370,
  },
  {
    id: 7,
    title: 'Comedor',
    subtitle: 'Comedor trabajadores tajo abierto',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249294/Pukaqaqa/comedor_hs94ys.jpg',
    x: 332,
    y: 403,
  },
  {
    id: 8,
    title: 'Depósito de desechos',
    subtitle: 'Depósito de desechos y herramientas',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249294/Pukaqaqa/desechos_jriq2x.jpg',
    x: 296,
    y: 439,
  },
  {
    id: 9,
    title: 'PLAT-299',
    subtitle: 'Plataforma remediada',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249297/Pukaqaqa/plat299_k8wd13.jpg',
    x: 398,
    y: 441,
  },
  {
    id: 9,
    title: 'PLAT-248',
    subtitle: 'Plataforma remediada',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249296/Pukaqaqa/plat248_degmw5.jpg',
    x: 739,
    y: 274,
  },
  {
    id: 10,
    title: 'PLAT-241',
    subtitle: 'Plataforma remediada',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249295/Pukaqaqa/plat241_rhzmcd.jpg',
    x: 896,
    y: 283,
  },
  {
    id: 11,
    title: 'PLAT-240',
    subtitle: 'Plataforma remediada',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249295/Pukaqaqa/plat240_fnovti.jpg',
    x: 996,
    y: 270,
  },
  {
    id: 12,
    title: 'Volquete',
    subtitle: 'Volquete de Ecohñan',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249298/Pukaqaqa/volquete_xnkmvc.jpg',
    x: 1188,
    y: 302,
  },
  {
    id: 13,
    title: 'Ingreso Ecohñan',
    subtitle: 'Ingreso a labores Ecohñan',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249294/Pukaqaqa/ingreso_tkcokw.jpg',
    x: 1126,
    y: 404,
  },
  {
    id: 14,
    title: 'Instalaciones Nexa',
    subtitle: 'Instalaciones Nexa',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249294/Pukaqaqa/instalaciones_rjonkx.jpg',
    x: 1626,
    y: 385,
  },
  {
    id: 15,
    title: 'Contenedores',
    subtitle: 'Contenedores Nexa',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249294/Pukaqaqa/contenedores_txu4sc.jpg',
    x: 1642,
    y: 388,
  },
  {
    id: 16,
    title: 'Instalaciones Nexa',
    subtitle: 'Instalaciones Nexa',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249294/Pukaqaqa/instalaciones1_n1jiz1.jpg',
    x: 1861,
    y: 336,
  },
  {
    id: 17,
    title: 'Pasivo',
    subtitle: 'Pasivo Nexa',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249295/Pukaqaqa/pasivo_jwfsrc.jpg',
    x: 1731,
    y: 244,
  },
  {
    id: 11,
    title: 'PLAT-451',
    subtitle: 'PLAT-451 Plataforma remediada',
    img: 'https://res.cloudinary.com/eparionad/image/upload/v1658249297/Pukaqaqa/plat451_jhnxjy.jpg',
    x: 1711,
    y: 216,
  },
];
